In [1]:
#NumPy(Numerical Pythond)
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
print(np.__version__)

2.3.0


In [4]:
arr = np.array((1,2,3,4,5))#we can pass any array like object to make ndarray like list,tuple,etc.

print(arr)

[1 2 3 4 5]


In [5]:
#Dimensions in array:
arr = np.array(42) #0-D array or Scalars
print(arr)

42


In [6]:
arr = np.array([1,2,3,4,5]) #1-D array or uni-dimensional array which have 0-D arrays as elements.
print(arr)

[1 2 3 4 5]


In [9]:
arr = np.array([[1,2,3],[4,5,6]]) 
#2-D array which have 1-D arrays as elements.
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
#3-D array which have 2-D arrays as elements.
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
#ndim attribute that returns no. of dimensions
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
