In [ ]:
#NumPy(Numerical Python)
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
print(np.__version__)

2.3.0


In [5]:
arr = np.array((1,2,3,4,5))#we can pass any array like object to make ndarray like list,tuple,etc.

print(arr)

[1 2 3 4 5]


In [23]:
#Dimensions in array:

In [ ]:
#0-D array or Scalars
arr = np.array(42) 
print(arr)

42


In [ ]:
#1-D array or uni-dimensional array which have 0-D arrays as elements.
arr = np.array([1,2,3,4,5]) 
print(arr)

[1 2 3 4 5]


In [ ]:
#2-D array which have 1-D arrays as elements.
arr = np.array([[1,2,3],[4,5,6]]) 
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3-D array which have 2-D arrays as elements.
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [10]:
#ndim attribute that returns no. of dimensions
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
#Setting dimension of array by using ndmin argument.
arr = np.array([1,2,3,4,5],ndmin=5)

print(arr)
print("Number of dimension: ", arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of dimension:  5


In [22]:
#NumPy Array indexing:

In [ ]:
#1-D array index
arr = np.array([1,2,3,4,5])

print(arr[0])
print(arr[1])
print(arr[2]+arr[3])

1
2
7


In [15]:
#2-D array indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print("2nd element of 1st row:", arr[0,1])
print("element on 2nd row 5th column:", arr[1,4])

2nd element of 1st row: 2
element on 2nd row 5th column: 10


In [17]:
#3-D array indexing
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0,1,2])

6


In [19]:
#Negative indexing:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,-1])

10


In [20]:
#Array Slicing:

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
#The result includes the start index, but excludes the end index.

[2 3 4 5]


In [25]:
print(arr[4:])

[5 6 7]


In [26]:
print(arr[:4])

[1 2 3 4]


In [27]:
#Negative Slicing
print(arr[-3:-1])

[5 6]


In [28]:
#Step
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]


In [29]:
print(arr[::2])

[1 3 5 7]


In [30]:
#Slicing 2-D array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
#Row slicing
print(arr[0:2, 2])

[3 8]


In [ ]:
#Row slicing + column slicing
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]
